name = "SpectralKit"
uuid = "5c252ae7-b5b6-46ab-a016-b0e3d78320b7"
version = "0.16.1"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
ArgCheck = "1, 2"
Compat = "4.18.0"
DocStringExtensions = "0.8, 0.9"
OrderedCollections = "1"
StaticArrays = "1"
julia = "1.10"
